/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package software;

import AppPackage.AnimationClass;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.Timer;
import java.util.TimerTask;
import rojerusan.RSPanelsSlider;
/**
 *
 * @author Dell
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
        this.setLocationRelativeTo(this);
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelGradiente2 = new rspanelgradiente.RSPanelGradiente();
        IconLogo = new javax.swing.JLabel();
        LabelUsuario = new javax.swing.JLabel();
        LabelContraseña = new javax.swing.JLabel();
        ButtonMenu = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ButtonAcceder = new javax.swing.JButton();
        TextFieldUsuario = new rojeru_san.RSMTextFull();
        IconUsuario = new RSMaterialComponent.RSLabelIcon();
        IconContraseña = new RSMaterialComponent.RSLabelIcon();
        PassViewContraseña = new rojeru_san.RSMPassView();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        IconFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelGradiente2.setColorPrimario(new java.awt.Color(199, 57, 133));
        rSPanelGradiente2.setColorSecundario(new java.awt.Color(62, 10, 111));
        rSPanelGradiente2.setGradiente(rspanelgradiente.RSPanelGradiente.Gradiente.HORIZONTAL);
        rSPanelGradiente2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1.png"))); // NOI18N
        IconLogo.setText("jLabel1");
        rSPanelGradiente2.add(IconLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 130, 130));

        LabelUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        LabelUsuario.setText("Usuario:");
        rSPanelGradiente2.add(LabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        LabelContraseña.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelContraseña.setForeground(new java.awt.Color(255, 255, 255));
        LabelContraseña.setText("Contraseña:");
        rSPanelGradiente2.add(LabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        ButtonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menucircularbutton_79284 (1).png"))); // NOI18N
        ButtonMenu.setBorderPainted(false);
        ButtonMenu.setContentAreaFilled(false);
        ButtonMenu.setFocusPainted(false);
        ButtonMenu.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menucircularbutton_79284 (1).png"))); // NOI18N
        ButtonMenu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menublackcircularbutton_104737 (2).png"))); // NOI18N
        ButtonMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonMenuMouseClicked(evt);
            }
        });
        ButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMenuActionPerformed(evt);
            }
        });
        rSPanelGradiente2.add(ButtonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 35, 40));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Contact-book-2_icon-icons.com_52161.png"))); // NOI18N
        jLabel7.setToolTipText("Contáctanos");
        rSPanelGradiente2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 160, -1, 40));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconfinder-bl-1645-search-seo-magnifier-earth-globe-internet-4575058_121505.png"))); // NOI18N
        jLabel9.setToolTipText("Página web");
        rSPanelGradiente2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 120, -1, 35));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/server-bug_47935.png"))); // NOI18N
        jLabel8.setToolTipText("Reportar error");
        rSPanelGradiente2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 80, -1, 32));

        ButtonAcceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/F.png"))); // NOI18N
        ButtonAcceder.setBorderPainted(false);
        ButtonAcceder.setContentAreaFilled(false);
        ButtonAcceder.setFocusPainted(false);
        ButtonAcceder.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/E.png"))); // NOI18N
        ButtonAcceder.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/E.png"))); // NOI18N
        ButtonAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAccederActionPerformed(evt);
            }
        });
        rSPanelGradiente2.add(ButtonAcceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 420, 100, -1));

        TextFieldUsuario.setForeground(new java.awt.Color(255, 255, 255));
        TextFieldUsuario.setText("Oscar");
        TextFieldUsuario.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        TextFieldUsuario.setBotonColor(new java.awt.Color(255, 255, 255));
        TextFieldUsuario.setColorTransparente(true);
        TextFieldUsuario.setOpaque(false);
        TextFieldUsuario.setPlaceholder("Escriba su usuario...");
        TextFieldUsuario.setSelectionColor(new java.awt.Color(0, 120, 215));
        TextFieldUsuario.setSoloLetras(true);
        TextFieldUsuario.setxDarkIcon(true);
        rSPanelGradiente2.add(TextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 190, -1));

        IconUsuario.setForeground(new java.awt.Color(255, 255, 255));
        IconUsuario.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ACCOUNT_CIRCLE);
        IconUsuario.setSizeIcon(38.0F);
        rSPanelGradiente2.add(IconUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        IconContraseña.setForeground(new java.awt.Color(255, 255, 255));
        IconContraseña.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.VPN_KEY);
        IconContraseña.setSizeIcon(38.0F);
        rSPanelGradiente2.add(IconContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        PassViewContraseña.setForeground(new java.awt.Color(255, 255, 255));
        PassViewContraseña.setText("Hernan217");
        PassViewContraseña.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        PassViewContraseña.setBotonColor(new java.awt.Color(255, 255, 255));
        PassViewContraseña.setOpaque(false);
        PassViewContraseña.setSelectionColor(new java.awt.Color(0, 120, 215));
        PassViewContraseña.setxDarkIcon(true);
        rSPanelGradiente2.add(PassViewContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 190, -1));

        getContentPane().add(rSPanelGradiente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 575));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Bienvenido al CIE");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 17, -1, 15));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/A (1).png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        jButton4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/A (1).png"))); // NOI18N
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B (1).png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 5, 40, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/D (1).png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/C (1).png"))); // NOI18N
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/C (1).png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 5, 40, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 49, 760, 1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 759, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("¿Qué es el CIE?");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 10, 145, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("<html><center>El CIE (Centro de Información Electoral) es un Software que se encarga de recopilar, analizar y plasmar los datos electorales alrededor del estado. Dando de forma eficaz la información recabada y analizada.<center><html>");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 720, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 100, -1, 180));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 100, -1, 180));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Eficacia");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 100, 50, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Seguridad");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 100, 70, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Eficiencia");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 100, 63, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("<html><center>CIE maneja toda la información mediante bases de datos en un ambiente técnico cerrado, de este modo la información permanece resguardada entre los distintos niveles de usuarios que creen, manejen y visualicen esta información.<center><html>");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 170, 140));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("<html><center>CIE está diseñado para obtener, manejar y presentar todos los datos de manera clara y concisa, dando a conocer al usuario, toda la información necesitada expresada en tablas, gráficas y flujos.<center><html>");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 170, 140));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("<html><center>CIE transforma toda la información manejada y la refleja de manera cómoda, veraz y concisa. Utilizando métodos de control y manejo que plasmen la información de forma rápida y clara ante los distintos tipos de usuarios.<center><html>");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 170, 140));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Compromiso de funcionalidad");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 290, 205, -1));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/G.png"))); // NOI18N
        jLabel18.setText("Flujo");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel18.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 15, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Aqui va un texto explicando cada funcion  JAJAJAJA");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 490, 110));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 758, 180));

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/H.png"))); // NOI18N
        jLabel19.setText("Reportes");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel19.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 15, 128, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Aqui va un texto explicando cada funcion  JAJAJAJA");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 490, 110));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 758, 180));

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/I.png"))); // NOI18N
        jLabel20.setText("Soporte");
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel20.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 15, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Aqui va un texto explicando cada funcion  JAJAJAJA");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 490, 110));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 758, 180));

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/J.png"))); // NOI18N
        jLabel21.setText("Control");
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel21.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 15, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Aqui va un texto explicando cada funcion  JAJAJAJA");
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 490, 110));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 758, 180));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 51, 758, 523));

        IconFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/0.jpg"))); // NOI18N
        jPanel1.add(IconFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 759, 575));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 759, 575));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonMenuActionPerformed

    private void ButtonAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAccederActionPerformed
        Principal principal = new Principal();
        
        if(TextFieldUsuario.getText().equals("Oscar"))
        {
            if(!PassViewContraseña.getText().equals("Hernan217"))
            {
                JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrecto.");
            } else {
                principal.setVisible(true);
                this.setVisible(false);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrecto.");
        }
    }//GEN-LAST:event_ButtonAccederActionPerformed

    private void ButtonMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMenuMouseClicked
        AnimationClass animacion = new AnimationClass();
        
        
        animacion.jLabelXRight(-40, 10, 10, 5, jLabel7);
        animacion.jLabelXRight(-40, 10, 10, 5, jLabel8);
        animacion.jLabelXRight(-40, 10, 10, 5, jLabel9);
        
        animacion.jLabelXLeft(10, -40, 10, 5, jLabel7);
        animacion.jLabelXLeft(10, -40, 10, 5, jLabel8);
        animacion.jLabelXLeft(10, -40, 10, 5, jLabel9);
    }//GEN-LAST:event_ButtonMenuMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int D = JOptionPane.YES_NO_OPTION;
        int R = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea salir?", "Salir", D);
        if(R==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setState(InicioSesion.ICONIFIED);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
        
        Timer timer = new Timer();
        TimerTask task = new TimerTask() {

            @Override
            public void run() {
                if(0 == jPanel4.getX())
                {
                    Animacion.Animacion.mover_izquierda(770, 0, 2, 2, jPanel5);
                    Animacion.Animacion.mover_izquierda(0, -770, 2, 2, jPanel4);
                    jPanel4.setAlignmentX(770);
                }else
                    if(0 == jPanel5.getX())
                    {
                        Animacion.Animacion.mover_izquierda(0, -770, 2, 2, jPanel5);
                        Animacion.Animacion.mover_izquierda(770, 0, 2, 2, jPanel6);
                        jPanel5.setAlignmentX(770);
                    }else
                        if(0 == jPanel6.getX())
                        {
                            Animacion.Animacion.mover_izquierda(0, -770, 2, 2, jPanel6);
                            Animacion.Animacion.mover_izquierda(770, 0, 2, 2, jPanel7);
                            jPanel6.setAlignmentX(770);
                        }else
                            if(0 == jPanel7.getX())
                            {
                                Animacion.Animacion.mover_izquierda(0, -770, 2, 2, jPanel7);
                                Animacion.Animacion.mover_izquierda(770, 0, 2, 2, jPanel4);
                                jPanel7.setAlignmentX(770);
                            }
            }
        };
        timer.schedule(task, 5000, 5000);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAcceder;
    private javax.swing.JButton ButtonMenu;
    private RSMaterialComponent.RSLabelIcon IconContraseña;
    private javax.swing.JLabel IconFondo;
    private javax.swing.JLabel IconLogo;
    private RSMaterialComponent.RSLabelIcon IconUsuario;
    private javax.swing.JLabel LabelContraseña;
    private javax.swing.JLabel LabelUsuario;
    private rojeru_san.RSMPassView PassViewContraseña;
    private rojeru_san.RSMTextFull TextFieldUsuario;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    static javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    static javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    static javax.swing.JPanel jPanel4;
    static javax.swing.JPanel jPanel5;
    static javax.swing.JPanel jPanel6;
    static javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente2;
    // End of variables declaration//GEN-END:variables
}
