package software;

import java.awt.Color;
import java.sql.Connection;
import java.util.*;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
/**
 *
 * @author Oscar Chan
 */
public class Principal extends javax.swing.JFrame implements Runnable{
    
    static DefaultCategoryDataset dataset2;
    static DefaultCategoryDataset dataset3;
    static DefaultPieDataset dataset;
    static ChartPanel chartpanel;
    static ChartPanel chartpanel2;
    static ChartPanel chartpanel3;
    static JFreeChart chart;
    static JFreeChart chart2;
    static JFreeChart chart3;
    String Hora, Minutos, Segundos, AmPm;
    Calendar Cal;
    Thread H1;
    
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        H1 = new Thread(this);
        H1.start();
        
        rSButtonGradientIcon_new1.setEnabled(false);
        rSButtonGradientIcon_new1.setSelected(true);
        rSPanelShadow1.setVisible(true);
        jPanel2.setVisible(true);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel10.setVisible(false);
        
        dataset2 = new DefaultCategoryDataset();
        dataset2.setValue(500000, "Votantes", "Mérida");
        dataset2.setValue(20000, "Votantes", "Ticul");
        dataset2.setValue(120000, "Votantes", "Kanasín");
        dataset2.setValue(25000, "Votantes", "Conkal");
        dataset2.setValue(80000, "Votantes", "Caucel");
        dataset2.setValue(30000, "Votantes", "Valladolid");
        
        chart2 = ChartFactory.createBarChart("Estadística de votantes por municipio", "Municipios", "Votantes", dataset2);
        chart2.getPlot().setBackgroundPaint(Color.white);
        
        chartpanel2 = new ChartPanel(chart2);
        
        jPanel9.add(chartpanel2);
       
        dataset = new DefaultPieDataset();
        dataset.setValue("PRI", new Double(500000));
        dataset.setValue("Partido Verde", new Double(20000));
        dataset.setValue("PAN", new Double(1200000));
        dataset.setValue("PRD", new Double(25000));
        dataset.setValue("Morena", new Double(80000));
        dataset.setValue("Nueva Alianza", new Double(30000));
        
        chart = ChartFactory.createPieChart("Estadística de votos por partido", dataset, true, true, false);
        chart.getPlot().setBackgroundPaint(Color.white);
        
        chartpanel = new ChartPanel(chart);
        
        jPanel8.add(chartpanel);
        
        dataset3 = new DefaultCategoryDataset();
        dataset3.setValue(500000, "Votantes", "11:00AM");
        dataset3.setValue(20000, "Votantes", "12:00PM");
        dataset3.setValue(120000, "Votantes", "1:00PM");
        dataset3.setValue(25000, "Votantes", "2:00PM");
        dataset3.setValue(80000, "Votantes", "3:00PM");
        dataset3.setValue(30000, "Votantes", "4:00PM");
        
        chart3 = ChartFactory.createAreaChart("Estadística de votantes por horario", "Horarios", "Votantes", dataset3);
        chart3.getPlot().setBackgroundPaint(Color.white);
        
        chartpanel3 = new ChartPanel(chart3);
        
        jPanel10.add(chartpanel3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        rSPanelGradiente1 = new rspanelgradiente.RSPanelGradiente();
        jLabel1 = new javax.swing.JLabel();
        rSLabelIcon1 = new RSMaterialComponent.RSLabelIcon();
        jSeparator1 = new javax.swing.JSeparator();
        rSButtonGradientIcon_new1 = new newscomponents.RSButtonGradientIcon_new();
        rSButtonGradientIcon_new2 = new newscomponents.RSButtonGradientIcon_new();
        rSButtonGradientIcon_new3 = new newscomponents.RSButtonGradientIcon_new();
        rSButtonGradientIcon_new4 = new newscomponents.RSButtonGradientIcon_new();
        rSButtonGradientIcon_new5 = new newscomponents.RSButtonGradientIcon_new();
        rSButtonGradientIcon_new6 = new newscomponents.RSButtonGradientIcon_new();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        rSPanelShadow1 = new RSMaterialComponent.RSPanelShadow();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        rSButtonMaterialTwo1 = new RSMaterialComponent.RSButtonMaterialTwo();
        rSButtonMaterialTwo2 = new RSMaterialComponent.RSButtonMaterialTwo();
        rSButtonMaterialTwo3 = new RSMaterialComponent.RSButtonMaterialTwo();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menucircularbutton_79284 (1).png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menublackcircularbutton_104737 (2).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 35, 40));

        rSPanelGradiente1.setColorPrimario(new java.awt.Color(199, 57, 133));
        rSPanelGradiente1.setColorSecundario(new java.awt.Color(62, 10, 111));
        rSPanelGradiente1.setGradiente(rspanelgradiente.RSPanelGradiente.Gradiente.HORIZONTAL);
        rSPanelGradiente1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 32));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        rSPanelGradiente1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        rSLabelIcon1.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ACCOUNT_CIRCLE);
        rSLabelIcon1.setSizeIcon(140.0F);
        rSPanelGradiente1.add(rSLabelIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 70, 128, 128));

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        rSPanelGradiente1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 215, 1));

        rSButtonGradientIcon_new1.setText("Principal");
        rSButtonGradientIcon_new1.setBorderPainted(false);
        rSButtonGradientIcon_new1.setColorPrimario(new java.awt.Color(141, 37, 123));
        rSButtonGradientIcon_new1.setColorPrimarioHover(new java.awt.Color(162, 58, 126));
        rSButtonGradientIcon_new1.setColorSecundario(new java.awt.Color(132, 34, 122));
        rSButtonGradientIcon_new1.setColorSecundarioHover(new java.awt.Color(132, 36, 124));
        rSButtonGradientIcon_new1.setFocusPainted(false);
        rSButtonGradientIcon_new1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rSButtonGradientIcon_new1.setGradiente(newscomponents.RSButtonGradientIcon_new.Gradiente.HORIZONTAL);
        rSButtonGradientIcon_new1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rSButtonGradientIcon_new1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        rSButtonGradientIcon_new1.setIconTextGap(90);
        rSButtonGradientIcon_new1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HOME);
        rSButtonGradientIcon_new1.setRippleColor(new java.awt.Color(224, 224, 224));
        rSButtonGradientIcon_new1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradientIcon_new1ActionPerformed(evt);
            }
        });
        rSPanelGradiente1.add(rSButtonGradientIcon_new1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-9, 245, 223, 40));

        rSButtonGradientIcon_new2.setText("Estadísticas");
        rSButtonGradientIcon_new2.setBorderPainted(false);
        rSButtonGradientIcon_new2.setColorPrimario(new java.awt.Color(132, 34, 122));
        rSButtonGradientIcon_new2.setColorPrimarioHover(new java.awt.Color(153, 55, 125));
        rSButtonGradientIcon_new2.setColorSecundario(new java.awt.Color(122, 30, 120));
        rSButtonGradientIcon_new2.setColorSecundarioHover(new java.awt.Color(122, 32, 122));
        rSButtonGradientIcon_new2.setFocusPainted(false);
        rSButtonGradientIcon_new2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rSButtonGradientIcon_new2.setGradiente(newscomponents.RSButtonGradientIcon_new.Gradiente.HORIZONTAL);
        rSButtonGradientIcon_new2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rSButtonGradientIcon_new2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        rSButtonGradientIcon_new2.setIconTextGap(65);
        rSButtonGradientIcon_new2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DATA_USAGE);
        rSButtonGradientIcon_new2.setRippleColor(new java.awt.Color(224, 224, 224));
        rSButtonGradientIcon_new2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradientIcon_new2ActionPerformed(evt);
            }
        });
        rSPanelGradiente1.add(rSButtonGradientIcon_new2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-9, 285, 223, 40));

        rSButtonGradientIcon_new3.setText("Flujo de Votantes");
        rSButtonGradientIcon_new3.setBorderPainted(false);
        rSButtonGradientIcon_new3.setColorPrimario(new java.awt.Color(122, 30, 120));
        rSButtonGradientIcon_new3.setColorPrimarioHover(new java.awt.Color(143, 51, 123));
        rSButtonGradientIcon_new3.setColorSecundario(new java.awt.Color(112, 27, 119));
        rSButtonGradientIcon_new3.setColorSecundarioHover(new java.awt.Color(112, 29, 121));
        rSButtonGradientIcon_new3.setFocusPainted(false);
        rSButtonGradientIcon_new3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rSButtonGradientIcon_new3.setGradiente(newscomponents.RSButtonGradientIcon_new.Gradiente.HORIZONTAL);
        rSButtonGradientIcon_new3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rSButtonGradientIcon_new3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        rSButtonGradientIcon_new3.setIconTextGap(18);
        rSButtonGradientIcon_new3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ASSIGNMENT_IND);
        rSButtonGradientIcon_new3.setRippleColor(new java.awt.Color(224, 224, 224));
        rSButtonGradientIcon_new3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradientIcon_new3ActionPerformed(evt);
            }
        });
        rSPanelGradiente1.add(rSButtonGradientIcon_new3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-9, 325, 223, 40));

        rSButtonGradientIcon_new4.setText("Base de Datos");
        rSButtonGradientIcon_new4.setBorderPainted(false);
        rSButtonGradientIcon_new4.setColorPrimario(new java.awt.Color(112, 27, 119));
        rSButtonGradientIcon_new4.setColorPrimarioHover(new java.awt.Color(133, 48, 122));
        rSButtonGradientIcon_new4.setColorSecundario(new java.awt.Color(103, 24, 117));
        rSButtonGradientIcon_new4.setColorSecundarioHover(new java.awt.Color(103, 26, 119));
        rSButtonGradientIcon_new4.setFocusPainted(false);
        rSButtonGradientIcon_new4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rSButtonGradientIcon_new4.setGradiente(newscomponents.RSButtonGradientIcon_new.Gradiente.HORIZONTAL);
        rSButtonGradientIcon_new4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rSButtonGradientIcon_new4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        rSButtonGradientIcon_new4.setIconTextGap(45);
        rSButtonGradientIcon_new4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DNS);
        rSButtonGradientIcon_new4.setRippleColor(new java.awt.Color(224, 224, 224));
        rSButtonGradientIcon_new4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradientIcon_new4ActionPerformed(evt);
            }
        });
        rSPanelGradiente1.add(rSButtonGradientIcon_new4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-9, 365, 223, 40));

        rSButtonGradientIcon_new5.setText("Soporte");
        rSButtonGradientIcon_new5.setBorderPainted(false);
        rSButtonGradientIcon_new5.setColorPrimario(new java.awt.Color(103, 24, 117));
        rSButtonGradientIcon_new5.setColorPrimarioHover(new java.awt.Color(124, 45, 120));
        rSButtonGradientIcon_new5.setColorSecundario(new java.awt.Color(94, 21, 116));
        rSButtonGradientIcon_new5.setColorSecundarioHover(new java.awt.Color(94, 23, 118));
        rSButtonGradientIcon_new5.setFocusPainted(false);
        rSButtonGradientIcon_new5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rSButtonGradientIcon_new5.setGradiente(newscomponents.RSButtonGradientIcon_new.Gradiente.HORIZONTAL);
        rSButtonGradientIcon_new5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rSButtonGradientIcon_new5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        rSButtonGradientIcon_new5.setIconTextGap(96);
        rSButtonGradientIcon_new5.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SUPERVISOR_ACCOUNT);
        rSButtonGradientIcon_new5.setRippleColor(new java.awt.Color(224, 224, 224));
        rSButtonGradientIcon_new5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradientIcon_new5ActionPerformed(evt);
            }
        });
        rSPanelGradiente1.add(rSButtonGradientIcon_new5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-9, 405, 223, 40));

        rSButtonGradientIcon_new6.setText("Configuración");
        rSButtonGradientIcon_new6.setBorderPainted(false);
        rSButtonGradientIcon_new6.setColorPrimario(new java.awt.Color(94, 21, 116));
        rSButtonGradientIcon_new6.setColorPrimarioHover(new java.awt.Color(115, 42, 119));
        rSButtonGradientIcon_new6.setColorSecundario(new java.awt.Color(84, 17, 114));
        rSButtonGradientIcon_new6.setColorSecundarioHover(new java.awt.Color(84, 19, 116));
        rSButtonGradientIcon_new6.setFocusPainted(false);
        rSButtonGradientIcon_new6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rSButtonGradientIcon_new6.setGradiente(newscomponents.RSButtonGradientIcon_new.Gradiente.HORIZONTAL);
        rSButtonGradientIcon_new6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rSButtonGradientIcon_new6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        rSButtonGradientIcon_new6.setIconTextGap(48);
        rSButtonGradientIcon_new6.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SETTINGS);
        rSButtonGradientIcon_new6.setRippleColor(new java.awt.Color(224, 224, 224));
        rSButtonGradientIcon_new6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradientIcon_new6ActionPerformed(evt);
            }
        });
        rSPanelGradiente1.add(rSButtonGradientIcon_new6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-9, 445, 223, 40));

        rSLabelTextIcon1.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelTextIcon1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rSLabelTextIcon1.setText("<html><p align='right'>Sin notificaciones</p><p align='right'>pendientes</p><hmtl>");
        rSLabelTextIcon1.setFocusable(false);
        rSLabelTextIcon1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        rSLabelTextIcon1.setIconTextGap(20);
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.NOTIFICATIONS_NONE);
        rSLabelTextIcon1.setSizeIcon(36.0F);
        rSPanelGradiente1.add(rSLabelTextIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 525, 200, 40));

        jPanel1.add(rSPanelGradiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 0, 215, 580));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/A (1).png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        jButton4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/A (1).png"))); // NOI18N
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B (1).png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 5, 40, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/D (1).png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/C (1).png"))); // NOI18N
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/C (1).png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 5, 40, -1));

        rSPanelShadow1.setOpaque(false);
        rSPanelShadow1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        rSPanelShadow1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 950, 510));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 680, 430));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 680, 430));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 680, 430));

        rSButtonMaterialTwo1.setText("Municipios");
        rSButtonMaterialTwo1.setSelected(true);
        rSButtonMaterialTwo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialTwo1ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMaterialTwo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 5, 180, -1));

        rSButtonMaterialTwo2.setText("Partidos");
        rSButtonMaterialTwo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialTwo2ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMaterialTwo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 5, 180, -1));

        rSButtonMaterialTwo3.setText("Horarios");
        rSButtonMaterialTwo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialTwo3ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMaterialTwo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 5, 180, -1));

        rSPanelShadow1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 950, 510));
        rSPanelShadow1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 950, 510));
        rSPanelShadow1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 950, 510));
        rSPanelShadow1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 950, 510));
        rSPanelShadow1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 950, 510));

        jPanel1.add(rSPanelShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 50, 960, 520));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/36a.png"))); // NOI18N
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 0, -1, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/fondo.jpg"))); // NOI18N
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int D = JOptionPane.YES_NO_OPTION;
        int R = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea salir?", "Salir", D);
        if(R==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setState(InicioSesion.ICONIFIED);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int N = rSPanelGradiente1.getX();
        if(N > -100)
        {
            Animacion.Animacion.mover_izquierda(0, -150, 1, 1, rSPanelGradiente1);
            H1.resume();
            Animacion.Animacion.mover_izquierda(43, -107, 1, 1, rSLabelIcon1);
            jLabel1.setVisible(true);
            
        }
        else
        {
            Animacion.Animacion.mover_derecha(-150, 0, 1, 1, rSPanelGradiente1);
            H1.suspend();
            Animacion.Animacion.mover_derecha(-107, 43, 1, 1, rSLabelIcon1);
            jLabel1.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rSButtonGradientIcon_new1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradientIcon_new1ActionPerformed
        if(rSPanelGradiente1.getX()==0)
        {
            Animacion.Animacion.mover_izquierda(0, -150, 1, 1, rSPanelGradiente1);
            Animacion.Animacion.mover_izquierda(43, -107, 1, 1, rSLabelIcon1);
            jLabel1.setVisible(true);
            H1.resume();
        }
        
        rSButtonGradientIcon_new1.setSelected(true);
        rSButtonGradientIcon_new1.setEnabled(false);
        
        rSButtonGradientIcon_new2.setEnabled(true);
        rSButtonGradientIcon_new2.setSelected(false);
        
        rSButtonGradientIcon_new3.setEnabled(true);
        rSButtonGradientIcon_new3.setSelected(false);
        
        rSButtonGradientIcon_new4.setEnabled(true);
        rSButtonGradientIcon_new4.setSelected(false);
        
        rSButtonGradientIcon_new5.setEnabled(true);
        rSButtonGradientIcon_new5.setSelected(false);
        
        rSButtonGradientIcon_new6.setEnabled(true);
        rSButtonGradientIcon_new6.setSelected(false);
        
        jPanel2.setVisible(true);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
    }//GEN-LAST:event_rSButtonGradientIcon_new1ActionPerformed

    private void rSButtonGradientIcon_new2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradientIcon_new2ActionPerformed
        if(rSPanelGradiente1.getX()==0)
        {
            Animacion.Animacion.mover_izquierda(0, -150, 1, 1, rSPanelGradiente1);
            Animacion.Animacion.mover_izquierda(43, -107, 1, 1, rSLabelIcon1);
            jLabel1.setVisible(true);
            H1.resume();
        }
        
        rSPanelShadow1.setVisible(true);
        
        rSButtonGradientIcon_new1.setEnabled(true);
        rSButtonGradientIcon_new1.setSelected(false);
        
        rSButtonGradientIcon_new2.setEnabled(false);
        rSButtonGradientIcon_new2.setSelected(true);
        
        rSButtonGradientIcon_new3.setEnabled(true);
        rSButtonGradientIcon_new3.setSelected(false);
        
        rSButtonGradientIcon_new4.setEnabled(true);
        rSButtonGradientIcon_new4.setSelected(false);
        
        rSButtonGradientIcon_new5.setEnabled(true);
        rSButtonGradientIcon_new5.setSelected(false);
        
        rSButtonGradientIcon_new6.setEnabled(true);
        rSButtonGradientIcon_new6.setSelected(false);
        
        jPanel2.setVisible(false);
        jPanel3.setVisible(true);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
    }//GEN-LAST:event_rSButtonGradientIcon_new2ActionPerformed

    private void rSButtonGradientIcon_new3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradientIcon_new3ActionPerformed
        if(rSPanelGradiente1.getX()==0)
        {
            Animacion.Animacion.mover_izquierda(0, -150, 1, 1, rSPanelGradiente1);
            Animacion.Animacion.mover_izquierda(43, -107, 1, 1, rSLabelIcon1);
            jLabel1.setVisible(true);
            H1.resume();
        }
        
        rSPanelShadow1.setVisible(true);
        
        rSButtonGradientIcon_new1.setEnabled(true);
        rSButtonGradientIcon_new1.setSelected(false);
        
        rSButtonGradientIcon_new2.setEnabled(true);
        rSButtonGradientIcon_new2.setSelected(false);
        
        rSButtonGradientIcon_new3.setEnabled(false);
        rSButtonGradientIcon_new3.setSelected(true);
        
        rSButtonGradientIcon_new4.setEnabled(true);
        rSButtonGradientIcon_new4.setSelected(false);
        
        rSButtonGradientIcon_new5.setEnabled(true);
        rSButtonGradientIcon_new5.setSelected(false);
        
        rSButtonGradientIcon_new6.setEnabled(true);
        rSButtonGradientIcon_new6.setSelected(false);
        
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(true);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
    }//GEN-LAST:event_rSButtonGradientIcon_new3ActionPerformed

    private void rSButtonGradientIcon_new4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradientIcon_new4ActionPerformed
        if(rSPanelGradiente1.getX()==0)
        {
            Animacion.Animacion.mover_izquierda(0, -150, 1, 1, rSPanelGradiente1);
            Animacion.Animacion.mover_izquierda(43, -107, 1, 1, rSLabelIcon1);
            jLabel1.setVisible(true);
            H1.resume();
        }
        
        rSPanelShadow1.setVisible(true);
        
        rSButtonGradientIcon_new1.setEnabled(true);
        rSButtonGradientIcon_new1.setSelected(false);
        
        rSButtonGradientIcon_new2.setEnabled(true);
        rSButtonGradientIcon_new2.setSelected(false);
        
        rSButtonGradientIcon_new3.setEnabled(true);
        rSButtonGradientIcon_new3.setSelected(false);
        
        rSButtonGradientIcon_new4.setEnabled(false);
        rSButtonGradientIcon_new4.setSelected(true);
        
        rSButtonGradientIcon_new5.setEnabled(true);
        rSButtonGradientIcon_new5.setSelected(false);
        
        rSButtonGradientIcon_new6.setEnabled(true);
        rSButtonGradientIcon_new6.setSelected(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(true);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
    }//GEN-LAST:event_rSButtonGradientIcon_new4ActionPerformed

    private void rSButtonGradientIcon_new5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradientIcon_new5ActionPerformed
        if(rSPanelGradiente1.getX()==0)
        {
            Animacion.Animacion.mover_izquierda(0, -150, 1, 1, rSPanelGradiente1);
            Animacion.Animacion.mover_izquierda(43, -107, 1, 1, rSLabelIcon1);
            jLabel1.setVisible(true);
            H1.resume();
        }
        
        rSPanelShadow1.setVisible(true);
        
        rSButtonGradientIcon_new1.setEnabled(true);
        rSButtonGradientIcon_new1.setSelected(false);
        
        rSButtonGradientIcon_new2.setEnabled(true);
        rSButtonGradientIcon_new2.setSelected(false);
        
        rSButtonGradientIcon_new3.setEnabled(true);
        rSButtonGradientIcon_new3.setSelected(false);
        
        rSButtonGradientIcon_new4.setEnabled(true);
        rSButtonGradientIcon_new4.setSelected(false);
        
        rSButtonGradientIcon_new5.setEnabled(false);
        rSButtonGradientIcon_new5.setSelected(true);
        
        rSButtonGradientIcon_new6.setEnabled(true);
        rSButtonGradientIcon_new6.setSelected(false);
        
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(true);
        jPanel7.setVisible(false);
    }//GEN-LAST:event_rSButtonGradientIcon_new5ActionPerformed

    private void rSButtonGradientIcon_new6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradientIcon_new6ActionPerformed
        if(rSPanelGradiente1.getX()==0)
        {
            Animacion.Animacion.mover_izquierda(0, -150, 1, 1, rSPanelGradiente1);
            Animacion.Animacion.mover_izquierda(43, -107, 1, 1, rSLabelIcon1);
            jLabel1.setVisible(true);
            H1.resume();
        }
        
        rSPanelShadow1.setVisible(true);
        
        rSButtonGradientIcon_new1.setEnabled(true);
        rSButtonGradientIcon_new1.setSelected(false);
        
        rSButtonGradientIcon_new2.setEnabled(true);
        rSButtonGradientIcon_new2.setSelected(false);
        
        rSButtonGradientIcon_new3.setEnabled(true);
        rSButtonGradientIcon_new3.setSelected(false);
        
        rSButtonGradientIcon_new4.setEnabled(true);
        rSButtonGradientIcon_new4.setSelected(false);
        
        rSButtonGradientIcon_new5.setEnabled(true);
        rSButtonGradientIcon_new5.setSelected(false);
        
        rSButtonGradientIcon_new6.setEnabled(false);
        rSButtonGradientIcon_new6.setSelected(true);
        
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(true);
    }//GEN-LAST:event_rSButtonGradientIcon_new6ActionPerformed

    private void rSButtonMaterialTwo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialTwo1ActionPerformed
        jPanel9.setVisible(true);
        jPanel8.setVisible(false);
        jPanel10.setVisible(false);
    }//GEN-LAST:event_rSButtonMaterialTwo1ActionPerformed

    private void rSButtonMaterialTwo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialTwo2ActionPerformed
        jPanel9.setVisible(false);
        jPanel8.setVisible(true);
        jPanel10.setVisible(false);
    }//GEN-LAST:event_rSButtonMaterialTwo2ActionPerformed

    private void rSButtonMaterialTwo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialTwo3ActionPerformed
        jPanel9.setVisible(false);
        jPanel8.setVisible(false);
        jPanel10.setVisible(true);
    }//GEN-LAST:event_rSButtonMaterialTwo3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private newscomponents.RSButtonGradientIcon_new rSButtonGradientIcon_new1;
    private newscomponents.RSButtonGradientIcon_new rSButtonGradientIcon_new2;
    private newscomponents.RSButtonGradientIcon_new rSButtonGradientIcon_new3;
    private newscomponents.RSButtonGradientIcon_new rSButtonGradientIcon_new4;
    private newscomponents.RSButtonGradientIcon_new rSButtonGradientIcon_new5;
    private newscomponents.RSButtonGradientIcon_new rSButtonGradientIcon_new6;
    private RSMaterialComponent.RSButtonMaterialTwo rSButtonMaterialTwo1;
    private RSMaterialComponent.RSButtonMaterialTwo rSButtonMaterialTwo2;
    private RSMaterialComponent.RSButtonMaterialTwo rSButtonMaterialTwo3;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon1;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente1;
    private RSMaterialComponent.RSPanelShadow rSPanelShadow1;
    // End of variables declaration//GEN-END:variables

    @SuppressWarnings({"override", "SleepWhileInLoop"})
    public void run() {
        Thread CT = Thread.currentThread();
        while(CT == H1)
        {
            Calcular();
            jLabel1.setText("<html><center>" + Hora + "<p>" + Minutos + "<p>" + Segundos + "<p>" + AmPm + "<center><html>");
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {}
        }
    }

    private void Calcular() {
        Cal = new GregorianCalendar();
        Date Fecha = new Date();
        Cal.setTime(Fecha);
        AmPm = Cal.get(Calendar.AM_PM)==Calendar.AM?"AM":"PM";
        if(AmPm.equals("PM"))
        {
            int H = Cal.get(Calendar.HOUR_OF_DAY)-12;
            Hora = H>9?""+H:"0"+H;
        }
        else
        {
            Hora = Cal.get(Calendar.HOUR_OF_DAY)>9?""+Cal.get(Calendar.HOUR_OF_DAY):"0"+Cal.get(Calendar.HOUR_OF_DAY);
        }
        Minutos = Cal.get(Calendar.MINUTE)>9?""+Cal.get(Calendar.MINUTE):"0"+Cal.get(Calendar.MINUTE);
        Segundos = Cal.get(Calendar.SECOND)>9?""+Cal.get(Calendar.SECOND):"0"+Cal.get(Calendar.SECOND);
    }
}
